activities:
  Post to Slack:
    output: output
    activityRoot: .
    environment:
      path:
        - .
      pythonPath:
        - .
    action:
      command:
        - python
        - -m
        - robot
        - -d
        - output
        - --logtitle
        - Task log
        - slack.robot
condaConfig: conda.yaml
